version: '3.7'
services:
  camera-simulator:
    container_name: camera-simulator
    image: aler9/rtsp-simple-server
    ports:
      - "127.0.0.1:8554:8554"
  camera-simulator0:
    build:
      context: .
    image: openvino/ubuntu20_data_runtime:2021.4.2
    container_name: camera-simulator0
    network_mode: "host"
    entrypoint: ffmpeg
    command: "
        -nostdin
        -re -stream_loop -1
        -i /home/pipeline-server/sample-media/00-coca-cola-4465029-1920-15-bench.mp4
        -c copy
        -f rtsp
        -rtsp_transport
        tcp
        rtsp://localhost:8554/camera_0
        "
    depends_on:
      - camera-simulator
    volumes:
      - ./sample-media:/home/pipeline-server/sample-media
  camera-simulator1:
    build:
      context: .
    image: openvino/ubuntu20_data_runtime:2021.4.2
    container_name: camera-simulator1
    network_mode: "host"
    entrypoint: ffmpeg
    command: "
        -nostdin
        -re -stream_loop -1
        -i /home/pipeline-server/sample-media/01-vehicle-bike-1920-15-bench.mp4
        -c copy
        -f rtsp
        -rtsp_transport
        tcp
        rtsp://localhost:8554/camera_1
        "
    depends_on:
      - camera-simulator
    volumes:
      - ./sample-media:/home/pipeline-server/sample-media
  camera-simulator2:
    build:
      context: .
    image: openvino/ubuntu20_data_runtime:2021.4.2
    container_name: camera-simulator2
    network_mode: "host"
    entrypoint: ffmpeg
    command: "
        -nostdin
        -re -stream_loop -1
        -i /home/pipeline-server/sample-media/02-video_of_people_walking_855564-1920-15-bench.mp4
        -c copy
        -f rtsp
        -rtsp_transport
        tcp
        rtsp://localhost:8554/camera_2
        "
    depends_on:
      - camera-simulator
    volumes:
      - ./sample-media:/home/pipeline-server/sample-media
  camera-simulator3:
    build:
      context: .
    image: openvino/ubuntu20_data_runtime:2021.4.2
    container_name: camera-simulator3
    network_mode: "host"
    entrypoint: ffmpeg
    command: "
        -nostdin
        -re -stream_loop -1
        -i /home/pipeline-server/sample-media/03-barcode-1920-15-bench.mp4
        -c copy
        -f rtsp
        -rtsp_transport
        tcp
        rtsp://localhost:8554/camera_3
        "
    depends_on:
      - camera-simulator
    volumes:
      - ./sample-media:/home/pipeline-server/sample-media